/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as ProjectsStatusRouteImport } from './routes/projects.$status'
import { Route as DepartmentsSlugRouteImport } from './routes/departments.$slug'
import { Route as PropertiesIdNewsNewsIdRouteImport } from './routes/properties.$id.news.$newsId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsStatusRoute = ProjectsStatusRouteImport.update({
  id: '/projects/$status',
  path: '/projects/$status',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsSlugRoute = DepartmentsSlugRouteImport.update({
  id: '/departments/$slug',
  path: '/departments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdNewsNewsIdRoute = PropertiesIdNewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => PropertiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/projects/$status': typeof ProjectsStatusRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/properties/$id/news/$newsId': typeof PropertiesIdNewsNewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/projects/$status': typeof ProjectsStatusRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/properties/$id/news/$newsId': typeof PropertiesIdNewsNewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/gallery': typeof GalleryRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/projects/$status': typeof ProjectsStatusRoute
  '/properties/$id': typeof PropertiesIdRouteWithChildren
  '/properties/$id/news/$newsId': typeof PropertiesIdNewsNewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/gallery'
    | '/profile'
    | '/reset-password'
    | '/departments/$slug'
    | '/projects/$status'
    | '/properties/$id'
    | '/properties/$id/news/$newsId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/gallery'
    | '/profile'
    | '/reset-password'
    | '/departments/$slug'
    | '/projects/$status'
    | '/properties/$id'
    | '/properties/$id/news/$newsId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/gallery'
    | '/profile'
    | '/reset-password'
    | '/departments/$slug'
    | '/projects/$status'
    | '/properties/$id'
    | '/properties/$id/news/$newsId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  GalleryRoute: typeof GalleryRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DepartmentsSlugRoute: typeof DepartmentsSlugRoute
  ProjectsStatusRoute: typeof ProjectsStatusRoute
  PropertiesIdRoute: typeof PropertiesIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$status': {
      id: '/projects/$status'
      path: '/projects/$status'
      fullPath: '/projects/$status'
      preLoaderRoute: typeof ProjectsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$slug': {
      id: '/departments/$slug'
      path: '/departments/$slug'
      fullPath: '/departments/$slug'
      preLoaderRoute: typeof DepartmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id/news/$newsId': {
      id: '/properties/$id/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/properties/$id/news/$newsId'
      preLoaderRoute: typeof PropertiesIdNewsNewsIdRouteImport
      parentRoute: typeof PropertiesIdRoute
    }
  }
}

interface PropertiesIdRouteChildren {
  PropertiesIdNewsNewsIdRoute: typeof PropertiesIdNewsNewsIdRoute
}

const PropertiesIdRouteChildren: PropertiesIdRouteChildren = {
  PropertiesIdNewsNewsIdRoute: PropertiesIdNewsNewsIdRoute,
}

const PropertiesIdRouteWithChildren = PropertiesIdRoute._addFileChildren(
  PropertiesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  GalleryRoute: GalleryRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DepartmentsSlugRoute: DepartmentsSlugRoute,
  ProjectsStatusRoute: ProjectsStatusRoute,
  PropertiesIdRoute: PropertiesIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
